<<<<<<< HEAD
# Generated by Django 3.2.6 on 2021-09-15 13:40
=======
# Generated by Django 3.2.7 on 2021-09-15 11:51
>>>>>>> master

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
            ],
        ),
    ]
