# Generated by Django 3.2.7 on 2021-10-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.TextField(default='pending', max_length=10),
            preserve_default=False,
        ),
    ]
