# Generated by Django 3.2.7 on 2021-10-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='is_exemplar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='answers',
            name='is_referenced',
            field=models.IntegerField(),
        ),
    ]
