# Generated by Django 3.2.7 on 2021-09-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='guide_text',
        ),
    ]
