# Generated by Django 3.2.7 on 2021-09-26 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverSheetQuestion',
            fields=[
                ('question_num', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField()),
                ('is_short_answer', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='CoverSheetAnswers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('is_short_answer', models.BinaryField()),
                ('application_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.application')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.coversheetquestion')),
            ],
        ),
    ]
