# Generated by Django 3.2.7 on 2021-10-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_complete',
        ),
    ]
