# Generated by Django 3.2.6 on 2021-10-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_application_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_complete',
        ),
    ]
