# Generated by Django 3.2.7 on 2021-10-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='supervisor',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
