# Generated by Django 3.2.7 on 2021-10-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
