# Generated by Django 3.2.7 on 2021-10-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_question_is_template_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_template_question',
            field=models.IntegerField(null=True),
        ),
    ]
