# Generated by Django 3.2.7 on 2021-10-16 23:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211012_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='PCF',
        ),
        migrations.RemoveField(
            model_name='application',
            name='PIS',
        ),
        migrations.AddField(
            model_name='application',
            name='PCF_rt',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='PIS_rt',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
