# Generated by Django 3.2.6 on 2021-10-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211001_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='is_approved',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_complete',
            field=models.BooleanField(),
        ),
    ]
