# Generated by Django 3.2.7 on 2021-09-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210915_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ec_member',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='EC_Member',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
