# Generated by Django 3.2.7 on 2021-10-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='project_name',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
