# Generated by Django 3.2.7 on 2021-10-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='text',
        ),
        migrations.AddField(
            model_name='answers',
            name='multiple_choice_answer',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='short_answer_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
