# Generated by Django 3.2.7 on 2021-10-01 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_answers_answer_type'),
        ('accounts', '0003_auto_20211001_1236'),
    ]

    operations = [
    ]
