# Generated by Django 3.2.7 on 2021-10-26 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211017_1014'),
        ('accounts', '0003_question_is_template_question'),
    ]

    operations = [
    ]
