# Generated by Django 3.2.6 on 2021-10-01 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211001_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='answer_type',
        ),
    ]
