# Generated by Django 3.2.7 on 2021-09-19 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210918_0308'),
        ('accounts', '0007_auto_20210918_1234'),
    ]

    operations = [
    ]
