<<<<<<< HEAD
# Generated by Django 3.2.6 on 2021-09-11 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 3.2.7 on 2021-09-15 11:51

from django.db import migrations, models
>>>>>>> ac99bb226ca86e396b0c52b35f594fcaeecbfe71


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> ac99bb226ca86e396b0c52b35f594fcaeecbfe71
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('project_title', models.CharField(max_length=200)),
                ('project_date', models.DateField(auto_now=True)),
                ('progress', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('project_name', models.CharField(max_length=200)),
>>>>>>> ac99bb226ca86e396b0c52b35f594fcaeecbfe71
            ],
        ),
    ]
